### ISSUE TITLE
Compilation regexp for node does not match on `.mjs`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/frontmacs#91]
```
-*- mode: compilation; default-directory: "~/Code/microstates.js/" -*-
Compilation started at Fri Dec  1 11:35:55

node -r @std/esm play.mjs
ms.toggle().valueOf() =  false
ReferenceError: DoneAndDone is not defined
    at /Users/cowboyd/Code/microstates.js/play.mjs:17:21
    at Object.<anonymous> (/Users/cowboyd/Code/microstates.js/play.mjs)
    at Module._compile (module.js:612:30)

Compilation exited abnormally with code 1 at Fri Dec  1 11:35:56
```

**Comment by cowboyd** [comment]
fixed by #92 and #93
